import test,{after,before} from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";import os from "node:os";import path from "node:path";
const temp=fs.mkdtempSync(path.join(os.tmpdir(),"civicai-reports-"));
Object.assign(process.env,{NODE_ENV:"test",DB_PATH:path.join(temp,"db.json"),SQLITE_PATH:path.join(temp,"db.sqlite"),UPLOAD_PATH:path.join(temp,"uploads"),FRONTEND_URL:"http://localhost:5173",BCRYPT_ROUNDS:"4",AI_PROVIDER:""});
const {app}=await import("./server.js"); const {sql}=await import("./db.js"); let server,base;
before(()=>new Promise(resolve=>{server=app.listen(0,"127.0.0.1",()=>{base=`http://127.0.0.1:${server.address().port}/api`;resolve();});}));
after(()=>new Promise(resolve=>server.close(()=>{sql.close();fs.rmSync(temp,{recursive:true,force:true});resolve();})));
async function login(email,password="Civic@123"){const r=await fetch(`${base}/auth/login`,{method:"POST",headers:{"Content-Type":"application/json","X-CivicAI-CSRF":"1"},body:JSON.stringify({email,password})});return r.headers.get("set-cookie")?.split(";")[0]||"";}
async function json(url,{method="GET",cookie,body}={}){const r=await fetch(`${base}${url}`,{method,headers:{"Content-Type":"application/json","X-CivicAI-CSRF":"1",...(cookie?{Cookie:cookie}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,body:await r.json()};}
async function create(cookie,overrides={}){const form=new FormData();const value={title:"Dangerous pothole",description:"A deep pothole is forcing vehicles into the opposite lane near a school.",category:"pothole",latitude:"27.70",longitude:"85.34",address:"School Road, Ward 11",...overrides};for(const[k,v]of Object.entries(value))form.set(k,v);const r=await fetch(`${base}/reports`,{method:"POST",headers:{"X-CivicAI-CSRF":"1",Cookie:cookie},body:form});return {status:r.status,body:await r.json()};}

test("citizen creation is persisted with server-controlled fields and history",async()=>{const cookie=await login("asha@city.gov");const result=await create(cookie);assert.equal(result.status,201);assert.equal(result.body.data.citizenId,undefined);assert.equal(result.body.data.status,"submitted");assert.equal(result.body.data.priority,null);const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(result.body.data.id);assert.equal(row.citizen_id,"u_citizen");assert.equal(sql.prepare("SELECT COUNT(*) n FROM report_status_history WHERE report_id=?").get(row.id).n,1);});
test("authentication and validation protect report creation",async()=>{assert.equal((await create("")).status,401);const cookie=await login("asha@city.gov");assert.equal((await create(cookie,{title:"x"})).status,400);assert.equal((await create(cookie,{latitude:"999"})).status,400);assert.equal((await create(cookie,{category:"not-real"})).status,400);});
test("ownership prevents IDOR and staff status transitions are enforced",async()=>{const citizen=await login("asha@city.gov");const made=await create(citizen,{title:"Owned report number two"});const id=made.body.data.id;const now=Date.now();sql.prepare("INSERT INTO users VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run("u_other","Other Citizen","other@example.com",sql.prepare("SELECT password_hash FROM users WHERE id='u_citizen'").get().password_hash,"citizen","","","","","active",1,"password",now,now);const other=await login("other@example.com");assert.equal((await json(`/reports/${id}`,{cookie:other})).status,403);const authority=await login("ward11@city.gov");assert.equal((await json(`/reports/${id}/status`,{method:"POST",cookie:authority,body:{status:"resolved"}})).status,409);assert.equal((await json(`/reports/${id}/status`,{method:"POST",cookie:authority,body:{status:"under_review",reason:"Evidence review started."}})).status,200);assert.equal(sql.prepare("SELECT status FROM reports WHERE id=?").get(id).status,"under_review");});
test("filters, pagination, notifications and duplicate hints use database data",async()=>{const citizen=await login("asha@city.gov");const first=await create(citizen,{title:"First matching pothole report"});const second=await create(citizen,{title:"Second matching pothole report"});assert.ok(second.body.data.possibleDuplicateId===first.body.data.id||second.body.data.possibleDuplicateId);const list=await json("/reports/my?limit=1",{cookie:citizen});assert.equal(list.status,200);assert.equal(list.body.data.items.length,1);assert.ok(list.body.data.stats.total>=2);const notifications=await json("/notifications",{cookie:citizen});assert.ok(notifications.body.data.items.length>=2);});
test("evidence is signature-validated, securely named and access-controlled",async()=>{const citizen=await login("asha@city.gov");const form=new FormData();for(const[k,v]of Object.entries({title:"Report with photo evidence",description:"A damaged public structure needs inspection and repair by the responsible team.",category:"public_property",latitude:"27.70",longitude:"85.34",address:"Ward 11 public square"}))form.set(k,v);const png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAF/gL+X1zXAAAAAElFTkSuQmCC","base64");form.append("evidence",new Blob([png],{type:"image/png"}),"../../unsafe.png");const response=await fetch(`${base}/reports`,{method:"POST",headers:{"X-CivicAI-CSRF":"1",Cookie:citizen},body:form});const body=await response.json();assert.equal(response.status,201);const record=sql.prepare("SELECT * FROM report_evidence WHERE report_id=?").get(body.data.id);assert.match(record.storage_name,/^[a-f0-9-]+\.png$/);assert.equal(record.original_name,"unsafe.png");const other=await login("other@example.com");assert.equal((await fetch(`${base}${body.data.evidence[0].url.replace('/api','')}`,{headers:{Cookie:other}})).status,404);});
test("AI failure preserves the report and retry/override authorization is enforced",async()=>{const citizen=await login("asha@city.gov"),admin=await login("admin@city.gov");const made=await create(citizen,{title:"Electrical hazard report",description:"Citizen reports an exposed electrical wire near pedestrians at the ward office."});const id=made.body.data.id;for(let i=0;i<20&&sql.prepare("SELECT ai_status FROM reports WHERE id=?").get(id).ai_status!=="failed";i++)await new Promise(resolve=>setTimeout(resolve,5));const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(id);assert.ok(row);assert.equal(row.ai_status,"failed");assert.equal(row.ai_failure_code,"AI_CONFIGURATION_ERROR");assert.equal((await json(`/reports/${id}/ai/retry`,{method:"POST",cookie:citizen,body:{}})).status,403);assert.equal((await json(`/reports/${id}/ai/retry`,{method:"POST",cookie:admin,body:{}})).status,202);const override=await json(`/reports/${id}/override`,{method:"POST",cookie:admin,body:{field:"priority",value:"critical",reason:"Reviewed exposed-wire safety report."}});assert.equal(override.status,200);assert.equal(sql.prepare("SELECT priority FROM reports WHERE id=?").get(id).priority,95);assert.equal(sql.prepare("SELECT COUNT(*) count FROM report_overrides WHERE report_id=?").get(id).count,1);});
