import express from "express";
import multer from "multer";
import path from "node:path";
import { randomBytes, randomUUID } from "node:crypto";
import { sql } from "./db.js";
import { requireAuth } from "./auth.js";
import { createRateLimiter } from "./security.js";
import { getCategory } from "./analysis.js";
import { analyzeWithProvider } from "./ai-service.js";
import { removeEvidence, storeEvidence, uploadDir, validateEvidence } from "./evidence-storage.js";
import { CATEGORY_KEYS, cleanText, STATUS_TRANSITIONS, validateReportInput } from "./report-validation.js";

export const reportsRouter=express.Router();
const upload=multer({storage:multer.memoryStorage(),limits:{files:6,fileSize:8*1024*1024,fields:20,fieldSize:32*1024}});
const createLimiter=createRateLimiter({windowMs:60*60*1000,limit:Number(process.env.REPORT_RATE_LIMIT||10),key:(req)=>`${req.ip}:${req.user?.id||"anon"}`});

function fail(res,status,code,message,details){return res.status(status).json({success:false,error:{code,message,...(details?{details}:{})}});}
function ok(res,data,status=200,meta){return res.status(status).json({success:true,data,...(meta?{meta}:{})});}
function reportId(){for(let i=0;i<5;i++){const id=`CIV-${new Date().getUTCFullYear()}-${randomBytes(4).readUInt32BE()%1000000}`;if(!sql.prepare("SELECT 1 FROM reports WHERE id=?").get(id))return id;}return `CIV-${new Date().getUTCFullYear()}-${randomUUID().slice(0,8).toUpperCase()}`;}
function canView(user,row){return user?.role==="admin"||(user?.role==="citizen"&&row.citizen_id===user.id)||(user?.role==="authority"&&(row.department===user.department||row.assigned_authority_id===user.id));}
function canManage(user,row){return user?.role==="admin"||(user?.role==="authority"&&(row.department===user.department||row.assigned_authority_id===user.id));}
function addNotification(userId,reportId,kind,title,body,now=new Date().toISOString()){sql.prepare("INSERT INTO notifications (id,user_id,report_id,kind,title,body,read_at,created_at) VALUES (?,?,?,?,?,?,NULL,?)").run(`not_${randomUUID()}`,userId,reportId,kind,title,body,now);}
function evidence(id){return sql.prepare("SELECT id,original_name AS originalName,mime_type AS mimeType,file_size AS fileSize,kind,uploaded_at AS uploadedAt FROM report_evidence WHERE report_id=? ORDER BY uploaded_at").all(id).map(e=>({...e,url:`/api/reports/${encodeURIComponent(id)}/evidence/${encodeURIComponent(e.id)}`}));}
function history(id){return sql.prepare("SELECT id,old_status AS oldStatus,new_status AS newStatus,changed_by AS changedBy,reason,created_at AS createdAt FROM report_status_history WHERE report_id=? ORDER BY created_at").all(id);}
function notes(id){return sql.prepare("SELECT n.id,n.content,n.created_at AS createdAt,u.name AS author FROM report_notes n LEFT JOIN users u ON u.id=n.author_id WHERE n.report_id=? ORDER BY n.created_at DESC").all(id);}
function serialize(row,{detail=false,staff=false}={}){if(!row)return null;const priority=row.priority;const severity=priority==null?"pending":priority>=85?"critical":priority>=70?"high":priority>=45?"medium":"low";const value={id:row.id,citizenId:staff?row.citizen_id:undefined,title:row.title,description:row.description,category:row.category,categoryLabel:getCategory(row.category).label,status:row.status,priority, severity,department:row.department,assignedAuthorityId:staff?row.assigned_authority_id:undefined,latitude:row.latitude,longitude:row.longitude,address:row.address,location:row.address,locationData:{latitude:row.latitude,longitude:row.longitude,name:row.address},ward:row.ward,municipality:row.municipality,province:row.province,statusReason:row.status_reason,resolutionNotes:row.resolution_notes,resolvedDetail:row.resolution_notes?{note:row.resolution_notes,resolvedAt:row.resolved_at}:null,aiStatus:row.ai_status,aiCategory:row.ai_category,aiPriority:row.ai_priority,aiConfidence:row.ai_confidence,aiSummary:row.ai_summary||(row.ai_status==="failed"?"Automated analysis is temporarily unavailable; staff review is required.":"Automated analysis is pending."),aiDepartment:row.ai_department,aiAnalyzedAt:row.ai_analyzed_at,possibleDuplicateId:row.possible_duplicate_id,duplicateSimilarity:row.duplicate_similarity,createdAt:row.created_at,updatedAt:row.updated_at,reportedAt:row.submitted_at,submittedAt:row.submitted_at,acknowledgedAt:row.acknowledged_at,assignedAt:row.assigned_at,resolvedAt:row.resolved_at,closedAt:row.closed_at};if(detail){const ev=evidence(row.id);Object.assign(value,{evidence:ev,media:{photos:ev.filter(e=>e.kind==="citizen").length,voiceSec:null},timeline:history(row.id),activity:history(row.id).map(h=>({key:h.newStatus,at:h.createdAt,text:h.reason||`Status changed to ${h.newStatus}.`})),notes:staff?notes(row.id):undefined});}return value;}
function findDuplicate(input){const recent=sql.prepare("SELECT id,description,latitude,longitude FROM reports WHERE category=? AND created_at>=? ORDER BY created_at DESC LIMIT 50").all(input.category,new Date(Date.now()-30*86400000).toISOString());let best=null;const words=new Set(input.description.toLowerCase().split(/\W+/).filter(w=>w.length>3));for(const r of recent){const km=Math.hypot((r.latitude-input.latitude)*111,(r.longitude-input.longitude)*100);if(km>1)continue;const other=new Set(r.description.toLowerCase().split(/\W+/).filter(w=>w.length>3));const overlap=[...words].filter(w=>other.has(w)).length/Math.max(1,new Set([...words,...other]).size);const score=Math.round((Math.max(0,1-km)*.55+overlap*.45)*100);if(score>=55&&(!best||score>best.score))best={id:r.id,score};}return best;}
async function runAI(id){const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(id);if(!row)return;try{const ai=await analyzeWithProvider(row);sql.prepare("UPDATE reports SET ai_status='complete',ai_category=?,ai_priority=?,priority=?,ai_confidence=?,ai_summary=?,ai_department=?,ai_analyzed_at=?,updated_at=? WHERE id=?").run(ai.category,ai.priorityScore,ai.priorityScore,ai.confidence,ai.summary,ai.department,new Date().toISOString(),new Date().toISOString(),id);addNotification(row.citizen_id,id,"analysis","AI analysis completed",`CivicAI analysis is available for ${id}.`);}catch(error){sql.prepare("UPDATE reports SET ai_status='failed',updated_at=? WHERE id=?").run(new Date().toISOString(),id);console.error(JSON.stringify({event:"report_ai_failed",reportId:id,message:error.message}));}}

reportsRouter.post("/reports",requireAuth,createLimiter,upload.array("evidence",6),async(req,res,next)=>{let files=[];try{if(req.user.role!=="citizen")return fail(res,403,"CITIZEN_REQUIRED","Only citizen accounts can submit reports.");const parsed=validateReportInput(req.body||{});if(parsed.error)return fail(res,400,"VALIDATION_ERROR",parsed.error);files=await validateEvidence(req.files);const input=parsed.value;const duplicate=findDuplicate(input);const id=reportId();const now=new Date().toISOString();const category=getCategory(input.category);sql.exec("BEGIN IMMEDIATE");try{sql.prepare("INSERT INTO reports (id,citizen_id,title,description,category,status,priority,department,assigned_authority_id,latitude,longitude,address,ward,municipality,province,status_reason,resolution_notes,ai_status,possible_duplicate_id,duplicate_similarity,created_at,updated_at,submitted_at) VALUES (?,?,?,?,?,'submitted',NULL,?,NULL,?,?,?,?,?,?,NULL,NULL,'pending',?,?,?, ?,?)").run(id,req.user.id,input.title,input.description,input.category,category.department,input.latitude,input.longitude,input.address,input.ward,input.municipality,input.province,duplicate?.id||null,duplicate?.score||null,now,now,now);const ev=sql.prepare("INSERT INTO report_evidence (id,report_id,storage_name,original_name,mime_type,file_size,kind,uploaded_at) VALUES (?,?,?,?,?,?, 'citizen',?)");for(const f of files)ev.run(`ev_${randomUUID()}`,id,f.storageName,f.originalName,f.mimeType,f.size,now);sql.prepare("INSERT INTO report_status_history (id,report_id,old_status,new_status,changed_by,reason,created_at) VALUES (?,?,NULL,'submitted',?,?,?)").run(`hist_${randomUUID()}`,id,req.user.id,"Report submitted by citizen.",now);addNotification(req.user.id,id,"submitted","Your report has been submitted",`${id} was received successfully.`,now);sql.exec("COMMIT");}catch(error){sql.exec("ROLLBACK");throw error;}try{storeEvidence(files);}catch(error){sql.prepare("DELETE FROM reports WHERE id=?").run(id);removeEvidence(files);throw error;}console.info(JSON.stringify({event:"report_created",reportId:id,userId:req.user.id,evidenceCount:files.length}));setImmediate(()=>runAI(id));return ok(res,serialize(sql.prepare("SELECT * FROM reports WHERE id=?").get(id),{detail:true}),201);}catch(error){removeEvidence(files);next(error);}});

reportsRouter.get("/reports",requireAuth,(req,res)=>{const page=Math.max(1,Number(req.query.page)||1);const limit=Math.min(100,Math.max(1,Number(req.query.limit)||20));const where=[];const args=[];if(req.user.role==="citizen"){where.push("citizen_id=?");args.push(req.user.id);}else if(req.user.role==="authority"){where.push("(department=? OR assigned_authority_id=?)");args.push(req.user.department,req.user.id);}if(req.query.status){where.push("status=?");args.push(String(req.query.status));}if(req.query.category){if(!CATEGORY_KEYS.has(String(req.query.category)))return fail(res,400,"INVALID_FILTER","Invalid category filter.");where.push("category=?");args.push(String(req.query.category));}if(req.query.department&&req.user.role==="admin"){where.push("department=?");args.push(String(req.query.department).slice(0,100));}if(req.query.search){where.push("(id LIKE ? OR title LIKE ? OR description LIKE ?)");const q=`%${String(req.query.search).slice(0,100)}%`;args.push(q,q,q);}const clause=where.length?` WHERE ${where.join(" AND ")}`:"";const total=sql.prepare(`SELECT COUNT(*) count FROM reports${clause}`).get(...args).count;const rows=sql.prepare(`SELECT * FROM reports${clause} ORDER BY created_at DESC LIMIT ? OFFSET ?`).all(...args,limit,(page-1)*limit);ok(res,rows.map(r=>serialize(r,{staff:req.user.role!=="citizen"})),200,{page,limit,total,pages:Math.ceil(total/limit)});});
reportsRouter.get("/reports/my",requireAuth,(req,res)=>{if(req.user.role!=="citizen")return fail(res,403,"CITIZEN_REQUIRED","Citizen account required.");const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(100,Math.max(1,Number(req.query.limit)||20));const rows=sql.prepare("SELECT * FROM reports WHERE citizen_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?").all(req.user.id,limit,(page-1)*limit);const counts=sql.prepare("SELECT COUNT(*) total,SUM(status IN ('submitted','under_review','verified','assigned')) pending,SUM(status='in_progress') inProgress,SUM(status IN ('resolved','closed')) resolved,SUM(priority>=85) critical FROM reports WHERE citizen_id=?").get(req.user.id);ok(res,{items:rows.map(r=>serialize(r)),stats:{total:Number(counts.total||0),pending:Number(counts.pending||0),inProgress:Number(counts.inProgress||0),resolved:Number(counts.resolved||0),critical:Number(counts.critical||0)}},200,{page,limit,total:Number(counts.total||0)});});
reportsRouter.get("/reports-analytics",requireAuth,(req,res)=>{if(req.user.role!=="admin")return fail(res,403,"ADMIN_REQUIRED","Administrator access required.");const stats=sql.prepare("SELECT COUNT(*) totalReports,SUM(status NOT IN ('resolved','closed','rejected')) activeIssues,SUM(priority>=85 AND status NOT IN ('resolved','closed')) criticalIssues,SUM(status='in_progress') inProgress,SUM(status IN ('resolved','closed')) resolved,AVG(CASE WHEN resolved_at IS NOT NULL THEN julianday(resolved_at)-julianday(submitted_at) END) avgResolutionDays FROM reports").get();const categories=sql.prepare("SELECT category,COUNT(*) count FROM reports GROUP BY category ORDER BY count DESC").all();const statuses=sql.prepare("SELECT status,COUNT(*) count FROM reports GROUP BY status").all();const departments=sql.prepare("SELECT department,COUNT(*) assigned,SUM(status IN ('resolved','closed')) resolved FROM reports GROUP BY department").all();ok(res,{stats:{...stats,avgResolutionDays:Number((stats.avgResolutionDays||0).toFixed(1))},categories,statuses,departments,updatedAt:new Date().toISOString()});});
reportsRouter.get("/reports/:id",requireAuth,(req,res)=>{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row)return fail(res,404,"NOT_FOUND","Report not found.");if(!canView(req.user,row)){console.warn(JSON.stringify({event:"report_access_denied",reportId:req.params.id,userId:req.user.id}));return fail(res,403,"FORBIDDEN","You do not have access to this report.");}ok(res,serialize(row,{detail:true,staff:req.user.role!=="citizen"}));});
reportsRouter.get("/reports/:id/evidence/:evidenceId",requireAuth,(req,res)=>{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row||!canView(req.user,row))return fail(res,404,"NOT_FOUND","Evidence not found.");const item=sql.prepare("SELECT * FROM report_evidence WHERE id=? AND report_id=?").get(req.params.evidenceId,row.id);if(!item)return fail(res,404,"NOT_FOUND","Evidence not found.");res.type(item.mime_type).set("Content-Disposition",`inline; filename*=UTF-8''${encodeURIComponent(item.original_name)}`).sendFile(path.join(uploadDir,item.storage_name));});
reportsRouter.post("/reports/:id/status",requireAuth,(req,res)=>{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row)return fail(res,404,"NOT_FOUND","Report not found.");if(!canManage(req.user,row))return fail(res,403,"FORBIDDEN","You cannot update this report.");const next=String(req.body?.status||"");if(!STATUS_TRANSITIONS[row.status]?.includes(next))return fail(res,409,"INVALID_TRANSITION",`Cannot move this report from ${row.status} to ${next}.`);const reasonResult=req.body?.reason?cleanText(req.body.reason,{min:3,max:500,name:"Reason"}):{value:null};if(reasonResult.error)return fail(res,400,"VALIDATION_ERROR",reasonResult.error);const now=new Date().toISOString();sql.exec("BEGIN IMMEDIATE");try{sql.prepare("UPDATE reports SET status=?,status_reason=?,updated_at=?,acknowledged_at=CASE WHEN ?='under_review' THEN COALESCE(acknowledged_at,?) ELSE acknowledged_at END,assigned_at=CASE WHEN ?='assigned' THEN COALESCE(assigned_at,?) ELSE assigned_at END,resolved_at=CASE WHEN ?='resolved' THEN ? ELSE resolved_at END,closed_at=CASE WHEN ?='closed' THEN ? ELSE closed_at END WHERE id=?").run(next,reasonResult.value,now,next,now,next,now,next,now,next,now,row.id);sql.prepare("INSERT INTO report_status_history VALUES (?,?,?,?,?,?,?)").run(`hist_${randomUUID()}`,row.id,row.status,next,req.user.id,reasonResult.value,now);addNotification(row.citizen_id,row.id,"status",`Report status: ${next.replaceAll("_"," ")}`,reasonResult.value||`${row.id} is now ${next.replaceAll("_"," ")}.`,now);sql.exec("COMMIT");}catch(error){sql.exec("ROLLBACK");throw error;}console.info(JSON.stringify({event:"report_status_changed",reportId:row.id,from:row.status,to:next,actor:req.user.id}));ok(res,serialize(sql.prepare("SELECT * FROM reports WHERE id=?").get(row.id),{detail:true,staff:true}));});
reportsRouter.post("/reports/:id/assign",requireAuth,(req,res)=>{if(req.user.role!=="admin")return fail(res,403,"ADMIN_REQUIRED","Only administrators can assign reports.");const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row)return fail(res,404,"NOT_FOUND","Report not found.");const department=String(req.body?.department||"").trim().slice(0,100);if(!department)return fail(res,400,"VALIDATION_ERROR","Department is required.");const authority=req.body?.authorityId?sql.prepare("SELECT * FROM users WHERE id=? AND role='authority'").get(req.body.authorityId):null;if(req.body?.authorityId&&!authority)return fail(res,400,"VALIDATION_ERROR","Choose a valid authority.");const now=new Date().toISOString();sql.prepare("UPDATE reports SET department=?,assigned_authority_id=?,updated_at=? WHERE id=?").run(department,authority?.id||null,now,row.id);ok(res,serialize(sql.prepare("SELECT * FROM reports WHERE id=?").get(row.id),{detail:true,staff:true}));});
reportsRouter.post("/reports/:id/notes",requireAuth,(req,res)=>{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row||!canManage(req.user,row))return fail(res,403,"FORBIDDEN","You cannot add notes to this report.");const note=cleanText(req.body?.content,{min:2,max:2000,name:"Note"});if(note.error)return fail(res,400,"VALIDATION_ERROR",note.error);const item={id:`note_${randomUUID()}`,createdAt:new Date().toISOString()};sql.prepare("INSERT INTO report_notes VALUES (?,?,?,?,?)").run(item.id,row.id,req.user.id,note.value,item.createdAt);ok(res,{...item,content:note.value,author:req.user.name},201);});
reportsRouter.post("/reports/:id/resolution",requireAuth,upload.single("evidence"),async(req,res,next)=>{let files=[];try{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row||!canManage(req.user,row))return fail(res,403,"FORBIDDEN","You cannot add resolution evidence.");files=await validateEvidence(req.file?[req.file]:[]);if(files.length!==1)return fail(res,400,"INVALID_EVIDENCE","One resolution image is required.");const note=req.body?.note?cleanText(req.body.note,{min:2,max:1000,name:"Resolution note"}):{value:null};if(note.error)return fail(res,400,"VALIDATION_ERROR",note.error);storeEvidence(files);const f=files[0],now=new Date().toISOString(),id=`ev_${randomUUID()}`;try{sql.prepare("INSERT INTO report_evidence VALUES (?,?,?,?,?,?,'resolution',?)").run(id,row.id,f.storageName,f.originalName,f.mimeType,f.size,now);sql.prepare("UPDATE reports SET resolution_notes=COALESCE(?,resolution_notes),updated_at=? WHERE id=?").run(note.value,now,row.id);}catch(error){removeEvidence(files);throw error;}ok(res,{id,url:`/api/reports/${row.id}/evidence/${id}`,note:note.value,uploadedAt:now},201);}catch(error){next(error);}});
reportsRouter.post("/reports/:id/ai/retry",requireAuth,async(req,res)=>{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row)return fail(res,404,"NOT_FOUND","Report not found.");if(!canManage(req.user,row))return fail(res,403,"FORBIDDEN","You cannot retry analysis.");sql.prepare("UPDATE reports SET ai_status='pending' WHERE id=?").run(row.id);await runAI(row.id);ok(res,serialize(sql.prepare("SELECT * FROM reports WHERE id=?").get(row.id),{detail:true,staff:true}));});
reportsRouter.get("/notifications",requireAuth,(req,res)=>{const rows=sql.prepare("SELECT id,report_id AS reportId,kind,title,body,read_at AS readAt,created_at AS createdAt FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50").all(req.user.id);ok(res,{items:rows.map(n=>({...n,unread:!n.readAt}))});});
