export const ISSUE_STATUSES=["submitted","under_review","verified","assigned","in_progress","resolved","closed","rejected","reopened"].map(key=>({key,label:key.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}));
export const DEPARTMENTS=["Roads & Infrastructure","Waste Management","Water & Sanitation","Electricity","Public Safety","Environment","General Administration"];
export const STATUS_TRANSITIONS={submitted:["under_review","rejected"],under_review:["verified","rejected"],verified:["assigned","rejected"],assigned:["in_progress"],in_progress:["resolved"],resolved:["closed","reopened"],reopened:["assigned","in_progress"],closed:[],rejected:["reopened"]};
export const allowedTransitions=status=>STATUS_TRANSITIONS[status]||[];
export const ANALYTICS_FILTER_OPTIONS={categories:[],wards:[],departments:DEPARTMENTS,statuses:ISSUE_STATUSES};
async function api(path,options={}){const multipart=options.body instanceof FormData;const response=await fetch(`/api${path}`,{credentials:"include",...options,headers:{...(!multipart?{"Content-Type":"application/json"}:{}),"X-CivicAI-CSRF":"1",...options.headers}});const body=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(body.error?.message||"Request failed.");e.code=body.error?.code;throw e;}return body.data;}
function severity(priority){return priority>=85?"critical":priority>=70?"high":priority>=45?"medium":"low";}
function issue(r){return{...r,severity:severity(r.priority||0),reportCount:1,location:r.address||r.location,legitimacy:{score:null,legit:0,fake:0,total:0},aiConfidence:{classification:Math.round((r.aiConfidence||0)*100),severity:Math.round((r.aiConfidence||0)*100),department:Math.round((r.aiConfidence||0)*100)},explanation:r.aiSummary,activity:r.activity||[]};}
async function reports(query=""){return (await api(`/reports?limit=100${query}`)).map(issue);}
export async function getIssue(id){return issue(await api(`/reports/${encodeURIComponent(id)}`));}
export async function getIssueActivity(id){return (await getIssue(id)).activity;}
export async function getDepartmentIssues(department){return reports(`&department=${encodeURIComponent(department)}`);}
export async function assignDepartment(id,department){return issue(await api(`/reports/${encodeURIComponent(id)}/assign`,{method:"POST",body:JSON.stringify({department})}));}
export async function updateIssueStatus(id,status){return issue(await api(`/reports/${encodeURIComponent(id)}/status`,{method:"POST",body:JSON.stringify({status,reason:"Status updated by administrator."})}));}
export async function addInternalNote(id,note){return api(`/reports/${encodeURIComponent(id)}/notes`,{method:"POST",body:JSON.stringify({content:note})});}
export async function uploadResolutionImage(id,imageDataUrl,note=""){const blob=await(await fetch(imageDataUrl)).blob();const form=new FormData();form.append("evidence",blob,"resolution.jpg");form.append("note",note);return api(`/reports/${encodeURIComponent(id)}/resolution`,{method:"POST",body:form});}
export async function markIssueResolved(id,_resolvedBy,note=""){return issue(await api(`/reports/${encodeURIComponent(id)}/status`,{method:"POST",body:JSON.stringify({status:"resolved",reason:note||"Issue resolved by administrator."})}));}
export async function getCityOverview(){const a=await api("/reports-analytics");return{stats:{totalReports:Number(a.stats.totalReports||0),activeIssues:Number(a.stats.activeIssues||0),criticalIssues:Number(a.stats.criticalIssues||0),inProgress:Number(a.stats.inProgress||0),resolved:Number(a.stats.resolved||0),avgResolutionDays:Number(a.stats.avgResolutionDays||0)},updatedAt:a.updatedAt};}
export async function getCriticalIssues(){return(await reports("&status=in_progress")).filter(r=>r.priority>=85);}
export async function getPriorityQueue(){return(await reports()).filter(r=>!["resolved","closed","rejected"].includes(r.status)).sort((a,b)=>(b.priority||0)-(a.priority||0));}
export async function getAIInsights(){const a=await api("/reports-analytics");return a.categories.slice(0,3).map((c,i)=>({id:`category-${c.category}`,title:`${c.category.replaceAll("_"," ")} reports`,body:`${c.count} reports currently recorded in this category.`,metric:String(c.count),trend:"Database total",period:"Live",category:c.category,index:i}));}
export async function getLegacyAIInsights(){return getAIInsights();}
export async function getAnalytics(){const a=await api("/reports-analytics");const total=Number(a.stats.totalReports||0),resolved=Number(a.stats.resolved||0),active=Number(a.stats.activeIssues||0);return{total,trend:[],byCategory:a.categories,bySeverity:["critical","high","medium","low"].map(severity=>({severity,count:0})),departments:a.departments.map(d=>{const assigned=Number(d.assigned||0),done=Number(d.resolved||0);return{department:d.department,active:assigned-done,resolved:done,avgResolutionDays:0,resolutionRate:assigned?Math.round(done/assigned*100):0};}),community:{confirmed:0,awaiting:resolved,reportedNotResolved:0,confirmationRate:0},priorityDistribution:[],hotspots:[],resolution:{resolved,active,resolutionRate:total?Math.round(resolved/total*100):0,avgResolutionDays:Number(a.stats.avgResolutionDays||0)},insights:[],updatedAt:a.updatedAt};}
export async function searchCityReports(query){if(!query?.trim())return[];return reports(`&search=${encodeURIComponent(query.trim())}`);}
